[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "gunicorn CRM.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/"
healthcheckTimeout = 100

[env]
PORT = "8000"
DJANGO_ENV = "production"
DJANGO_SETTINGS_MODULE = "CRM.settings"
ALLOWED_HOSTS = "*"

[phases.setup]
nixPkgs = ["python3", "gcc", "mysql", "pkg-config", "mysql80", "mysql80-dev"]

[phases.install]
cmds = [
    "apt-get update",
    "apt-get install -y default-libmysqlclient-dev build-essential pkg-config",
    "python -m venv /opt/venv",
    ". /opt/venv/bin/activate",
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[start]
cmd = "gunicorn CRM.wsgi:application --bind 0.0.0.0:$PORT" 