# Generated by Django 5.1.7 on 2025-03-18 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='zipcode',
            new_name='Pincode',
        ),
    ]
