# Generated by Django 5.1.7 on 2025-03-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_rename_zipcode_record_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Pincode',
            field=models.CharField(max_length=6),
        ),
    ]
