# Generated by Django 5.1.6 on 2025-05-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0004_alter_record_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='Profile',
            field=models.ImageField(default=1, upload_to='static/images/'),
            preserve_default=False,
        ),
    ]
