# Generated by Django 5.1.6 on 2025-05-29 05:57

import Website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0005_record_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Profile',
            field=models.ImageField(blank=True, null=True, upload_to=Website.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='record',
            name='first_name',
            field=models.CharField(max_length=50, validators=[Website.models.starts_with_capital_M]),
        ),
    ]
