# Generated by Django 5.1.6 on 2025-06-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0006_alter_record_profile_alter_record_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
